[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
glam = { version = "0.30.8", default-features = false, features = ["nostd-libm"] }
fixed = "1.29.0"

[package]
name = "quiche-gl"
version = "0.0.1"
authors = ["Lynndox <lynndoxxy@gmail.com>"]
edition = "2024"

[lib]
# test = false
bench = false

[dependencies]
aarch64-cpu = "10.0.0"
bitflags = "2.9.4"
fixed = { workspace = true }
glam = { workspace = true, optional = true }

[features]
default = ["alloc", "glam"]
alloc = []
glam = ["dep:glam"]
glam-fast-math = ["glam/fast-math"]
